In [1]:
#Sort, Search & Counting Functions

In [2]:
import numpy as np

In [5]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [6]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [7]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [8]:
np.searchsorted(arr, 34)

12

In [9]:
arr1 = np.array([0, 345,454,0,0,0,0,0])

In [10]:
np.count_nonzero(arr1)

2

In [11]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [12]:
np.where(arr > 6)

(array([5, 8], dtype=int64),)

In [13]:
np.extract(arr > 6, arr)

array([ 72, 455])

In [14]:
#Numpy - Bite Swapping

In [15]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [16]:
arr.byteswap()

array([  67108864,   50331648,   67108864,   83886080,  100663296,
       1207959552,   50331648,   50331648, -956235776,   83886080,
        100663296,  100663296])

In [17]:
#Numpy - Copies & Views

In [18]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [19]:
a = np.copy(arr)

In [28]:
b = arr.view() # b = a

In [29]:
b

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [30]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [31]:
b[0] = 67

In [32]:
b

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [33]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [34]:
#Numpy - Matrix Library

In [35]:
import numpy.matlib as nm

In [36]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [37]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [39]:
#Numpy - Linear Algebra

In [40]:
arr1 = np.random.randint([[2,3], [4,5]])

In [43]:
arr2 = np.random.randint([[5,3], [2,5]])

In [44]:
np.dot(arr1, arr2)

array([[6, 2],
       [0, 8]])

In [45]:
arr1@arr2

array([[6, 2],
       [0, 8]])